"""nevers

Revision ID: 84e199f9cb91
Revises: ee9457e52d81
Create Date: 2023-06-20 11:48:03.975031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e199f9cb91'
down_revision = 'ee9457e52d81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cvc', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cvc')
    )
    op.add_column('events', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'roles', ['role_id'], ['id'])
    op.drop_column('events', 'role')
    op.add_column('projects', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('division', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'divisions', ['division'], ['cvc'])
    op.create_foreign_key(None, 'projects', 'roles', ['role_id'], ['id'])
    op.drop_column('projects', 'role')
    op.drop_column('projects', 'divisions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('divisions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'division')
    op.drop_column('projects', 'role_id')
    op.add_column('events', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'role_id')
    op.drop_table('divisions')
    # ### end Alembic commands ###
